# Generated by Django 5.2.8 on 2026-04-25 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationhistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='simulationhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simulationhistory',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simulationhistory',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
