from django.http import JsonResponse
from django.shortcuts import render
from .models import SimulationHistory
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Avg, Count

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/accounts/login/')
    else:
        form = UserCreationForm()

    return render(request, 'register.html', {'form': form})




def download_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="odts_report.pdf"'

    p = canvas.Canvas(response)

    # Latest simulation record
    latest = SimulationHistory.objects.last()

    y = 800

    p.setFont("Helvetica-Bold", 20)
    p.drawString(140, y, "ODTS MANAGEMENT REPORT")

    y -= 30
    p.setFont("Helvetica", 11)
    p.drawString(50, y, f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M')}")

    y -= 50

    if latest:

        p.setFont("Helvetica-Bold", 14)
        p.drawString(50, y, "Latest Simulation Data")

        y -= 30
        p.setFont("Helvetica", 12)

        p.drawString(60, y, f"Orders: {latest.orders}")
        y -= 20

        p.drawString(60, y, f"Workers: {latest.workers}")
        y -= 20

        p.drawString(60, y, f"Speed: {latest.speed}")
        y -= 20

        p.drawString(60, y, f"Time Required: {latest.time_required} hrs")
        y -= 20

        p.drawString(60, y, f"Status: {latest.status}")
        y -= 40

        p.setFont("Helvetica-Bold", 14)
        p.drawString(50, y, "AI Insight")

        y -= 25
        p.setFont("Helvetica", 12)

        if latest.status == "Delay":
            msg = "Increase workers or improve speed."
        else:
            msg = "Current setup is efficient."

        p.drawString(60, y, msg)

    else:
        p.setFont("Helvetica", 12)
        p.drawString(50, y, "No simulation history found.")

    y -= 60
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(50, y, "Generated by ODTS Smart Dashboard")

    p.save()
    return response
@login_required(login_url='/accounts/login/')
def home(request):
    result = None

    if request.method == "POST":
        orders = int(request.POST.get("orders"))
        workers = int(request.POST.get("workers"))
        speed = int(request.POST.get("speed"))

        total_capacity = workers * speed
        time_required = orders / total_capacity

        # Status
        if time_required <= 8:
            status = "No Delay"
        else:
            status = "Delay"

        # AI Recommendation
         # AI Recommendation Logic
        if time_required > 8 and workers < 5:
          recommendation = "Urgent: Increase workers and improve speed."

        elif time_required > 8:
          recommendation = "Increase processing speed to reduce delay."

        elif workers < 5:
          recommendation = "Consider adding more workers for better efficiency."

        elif speed < 3:
          recommendation = "Increase worker speed or automate process."

        else:
          recommendation = "Current setup is efficient. No action needed."
        # Risk Meter
        if time_required > 8 or workers <= 2:
          risk = "High Risk"

        elif time_required > 5 or workers <= 4:
          risk = "Medium Risk"

        else:
           risk = "Low Risk"
        recommended_workers = max(1, int((orders / (speed * 8)) + 0.999))
        # Cost Engine
        cost_per_worker = 500

        current_cost = workers * cost_per_worker
        optimized_cost = recommended_workers * cost_per_worker
        savings = current_cost - optimized_cost
        # Save History
        SimulationHistory.objects.create(
        user=request.user,
        orders=orders,
        workers=workers,
        speed=speed,
        time_required=round(time_required, 2),
        status=status
)
        result = {
            "time": round(time_required, 2),
            "status": status,
            "recommendation": recommendation,
            "risk": risk,
            "recommended_workers": recommended_workers,
            "current_cost": current_cost,
            "optimized_cost": optimized_cost,
            "savings": savings
        }

    history = SimulationHistory.objects.filter(
    user=request.user
).order_by('-id')[:5]

    return render(request, "home.html", {
        "result": result,
        "history": history
    })


def api_home(request):
    return JsonResponse({
        "message": "ODTS API is running",
        "endpoints": [
            "/api/simulate/",
            "/api/optimize/"
        ]
    })


def simulate(request):
    try:
        orders = int(request.GET.get("orders", 0))
        workers = int(request.GET.get("workers", 0))
        speed = float(request.GET.get("speed", 1))

        if orders < 0 or workers < 0 or speed <= 0:
            return JsonResponse({"error": "Invalid input values"})

        total_capacity = workers * speed

        if total_capacity == 0:
            return JsonResponse({"error": "Workers or speed cannot be zero"})

        time_required = orders / total_capacity

        if workers < 3:
            delay_risk = "HIGH"
        elif workers < 7:
            delay_risk = "MEDIUM"
        else:
            delay_risk = "LOW"

        bottleneck = (
            "Slow processing speed" if speed < 2 else
            "Insufficient workforce" if workers < 3 else
            "No major bottleneck"
        )

        return JsonResponse({
            "input": {
                "orders": orders,
                "workers": workers,
                "speed": speed
            },
            "results": {
                "total_capacity": total_capacity,
                "time_required": round(time_required, 2),
                "delay_risk": delay_risk,
                "bottleneck": bottleneck
            },
            "status": "Simulation completed successfully"
        })

    except Exception as e:
        return JsonResponse({"error": str(e)})


def optimize(request):
    orders = int(request.GET.get("orders", 100))
    speed = float(request.GET.get("speed", 1))

    best_workers = None
    best_time = float("inf")

    for workers in range(1, 21):
        capacity = workers * speed
        time_required = orders / capacity

        if time_required < best_time:
            best_time = time_required
            best_workers = workers

    return JsonResponse({
        "best_configuration": {
            "workers": best_workers,
            "time_required": round(best_time, 2)
        },
        "status": "Optimization completed"
    })
@login_required(login_url='/accounts/login/')
def admin_panel(request):

    total_users = User.objects.count()

    total_simulations = SimulationHistory.objects.count()

    total_delays = SimulationHistory.objects.filter(
        status="Delay"
    ).count()

    avg_time = SimulationHistory.objects.aggregate(
        Avg('time_required')
    )['time_required__avg']

    top_user = SimulationHistory.objects.values(
        'user__username'
    ).annotate(
        total=Count('id')
    ).order_by('-total').first()

    return render(request, 'admin_panel.html', {
        'total_users': total_users,
        'total_simulations': total_simulations,
        'total_delays': total_delays,
        'avg_time': round(avg_time or 0, 2),
        'top_user': top_user
    })
